// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CustomAnimatedNumberController from "./custom_animated_number_controller"
application.register("custom-animated-number", CustomAnimatedNumberController)

import DisplayPlanController from "./display_plan_controller"
application.register("display-plan", DisplayPlanController)

import DraggableController from "./draggable_controller"
application.register("draggable", DraggableController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LpScrollEffectController from "./lp_scroll_effect_controller"
application.register("lp-scroll-effect", LpScrollEffectController)

import NotificationsController from "./notifications_controller"
application.register("notifications", NotificationsController)

import SubButtonController from "./sub_button_controller"
application.register("sub-button", SubButtonController)
