// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DisplayPlanController from "./display_plan_controller"
application.register("display-plan", DisplayPlanController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import DraggableController from "./draggable_controller"
application.register("draggable", DraggableController)

import CustomAnimatedNumberController from "./custom_animated_number_controller"
application.register("custom-animated-number", CustomAnimatedNumberController)
